language: ruby
bundler_args: "--without production"
rvm:
- 2.1.2
env:
- DB=sqlite
- DB=postgresql
before_script:
- psql -c 'create database scriba_test' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
    secure: BcWxqVLn+GWMQqwoacKzEjHLyJ7h19VHnj9ENRqIw1KypILV3SDPGLDOrTsTNXJZt6JIBAj0J7At5KTkvNEv8LVcLKtMH5otNvi0X9FVVKU02JhXj5WtBipgWegQM8EcxCgFmTQDRVxaE4jy6Nx3lPRSzAGmAFUYEoE/wkO53jk=
  app: lit-caverns-7094
  on:
    repo: ZoeLeBlanc/scriba
